export const savedList = [
  {
    id: 1,
    images: [
      "https://images.unsplash.com/photo-1512918728676-2e1ec7d1d19b?auto=format&fit=crop&w=500&q=80",
      "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?auto=format&fit=crop&w=500&q=80",
    ],
    price: 1850,
    name: "Skyline Apartments",
    address: "233 St Perry Ave, Dallas, TX",
    beds: 3,
    baths: 2,
    description: "Modern skyline apartments with city view and balcony.",
    rules: "No smoking. No pets. Quiet hours 10pm-7am.",
    size: 90,
    rooms: 5,
    hasKitchen: true,
    kitchens: 1,
    hasBathroom: true,
    bathrooms: 2,
    hasClimate: true,
    hasTV: true,
    hasTVWireless: false,
    map: "https://maps.google.com/?q=233+St+Perry+Ave,+Dallas,+TX",
    owner: {
      id: "owner1",
      name: "John Doe",
      rating: 4.7,
    },
    cellphone: "+11234567890",
    saved: true,
  },
  {
    id: 2,
    images: [
      "https://images.unsplash.com/photo-1482062364825-616fd23b8fc1?auto=format&fit=crop&w=500&q=80",
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=500&q=80",
    ],
    price: 2330,
    name: "The Modern",
    address: "1000 Rentpath Way, Atlanta, GA",
    beds: 4,
    baths: 3,
    description: "Newly renovated modern apartment with city view.",
    rules: "No parties. Pet allowed. Quiet after 11pm.",
    size: 120,
    rooms: 6,
    hasKitchen: true,
    kitchens: 1,
    hasBathroom: true,
    bathrooms: 3,
    hasClimate: true,
    hasTV: false,
    hasTVWireless: false,
    map: "https://maps.google.com/?q=1000+Rentpath+Way,+Atlanta,+GA",
    owner: {
      id: "owner2",
      name: "Sarah Taylor",
      rating: 4.9,
    },
    cellphone: "+19876543210",
    saved: true,
  },
  {
    id: 3,
    images: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=500&q=80",
      "https://images.unsplash.com/photo-1551907234-be275bf27e18?auto=format&fit=crop&w=500&q=80",
    ],
    price: 1700,
    name: "Garden Villas",
    address: "45 Maple St, Austin, TX",
    beds: 2,
    baths: 1,
    description: "Garden villas with pool access and pet-friendly policy.",
    rules: "Pets allowed. No loud music after 9pm.",
    size: 80,
    rooms: 4,
    hasKitchen: true,
    kitchens: 1,
    hasBathroom: true,
    bathrooms: 1,
    hasClimate: true,
    hasTV: true,
    hasTVWireless: true,
    map: "https://maps.google.com/?q=45+Maple+St,+Austin,+TX",
    owner: {
      id: "owner3",
      name: "Emily Clarke",
      rating: 4.5,
    },
    cellphone: "+12345678900",
    saved: false,
  },
  {
    id: 4,
    images: [
      "https://images.unsplash.com/photo-1501183638714-207d0d66ee6f?auto=format&fit=crop&w=500&q=80",
      "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=500&q=80",
    ],
    price: 1950,
    name: "Lakeside Residency",
    address: "789 Lakeview Dr, Orlando, FL",
    beds: 2,
    baths: 2,
    description: "Residency with beautiful lake view and access to gym.",
    rules: "Quiet hours after 9pm. No smoking inside.",
    size: 110,
    rooms: 5,
    hasKitchen: true,
    kitchens: 1,
    hasBathroom: true,
    bathrooms: 2,
    hasClimate: true,
    hasTV: true,
    hasTVWireless: true,
    map: "https://maps.google.com/?q=789+Lakeview+Dr,+Orlando,+FL",
    owner: {
      id: "owner4",
      name: "Michael Scott",
      rating: 4.8,
    },
    cellphone: "+10987654321",
    saved: true,
  },
  {
    id: 5,
    images: [
      "https://images.unsplash.com/photo-1486308510493-c5ca6c9f35e9?auto=format&fit=crop&w=500&q=80",
      "https://images.unsplash.com/photo-1472224371017-08207f84aaae?auto=format&fit=crop&w=500&q=80",
    ],
    price: 2100,
    name: "Downtown Loft",
    address: "321 Central Ave, New York, NY",
    beds: 1,
    baths: 1,
    description: "Modern loft close to metro and city attractions.",
    rules: "No pets. No parties. Quiet building.",
    size: 75,
    rooms: 3,
    hasKitchen: true,
    kitchens: 1,
    hasBathroom: true,
    bathrooms: 1,
    hasClimate: false,
    hasTV: true,
    hasTVWireless: true,
    map: "https://maps.google.com/?q=321+Central+Ave,+New+York,+NY",
    owner: {
      id: "owner5",
      name: "Laura King",
      rating: 4.6,
    },
    cellphone: "+19871234567",
    saved: false,
  },
  {
    id: 6,
    images: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=500&q=80",
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=500&q=80",
    ],
    price: 2300,
    name: "Coastal Breeze",
    address: "410 Ocean Dr, Miami, FL",
    beds: 3,
    baths: 2,
    description: "Coastal apartment with stunning ocean views.",
    rules: "No pets. No loud parties. Min. 3-night stay.",
    size: 105,
    rooms: 5,
    hasKitchen: true,
    kitchens: 1,
    hasBathroom: true,
    bathrooms: 2,
    hasClimate: true,
    hasTV: true,
    hasTVWireless: false,
    map: "https://maps.google.com/?q=410+Ocean+Dr,+Miami,+FL",
    owner: {
      id: "owner6",
      name: "Anna Grey",
      rating: 4.7,
    },
    cellphone: "+13055555555",
    saved: false,
  },
  {
    id: 7,
    images: [
      "https://images.unsplash.com/photo-1523206489230-c0126f39b29b?auto=format&fit=crop&w=500&q=80",
      "https://images.unsplash.com/photo-1522770179533-24471fcdba45?auto=format&fit=crop&w=500&q=80",
    ],
    price: 2750,
    name: "Mountain View Condos",
    address: "150 Hillside Rd, Denver, CO",
    beds: 3,
    baths: 3,
    description: "Spacious condos with panoramic mountain views.",
    rules: "No smoking. No pets.",
    size: 140,
    rooms: 6,
    hasKitchen: true,
    kitchens: 1,
    hasBathroom: true,
    bathrooms: 3,
    hasClimate: true,
    hasTV: true,
    hasTVWireless: true,
    map: "https://maps.google.com/?q=150+Hillside+Rd,+Denver,+CO",
    owner: {
      id: "owner7",
      name: "David Lee",
      rating: 4.9,
    },
    cellphone: "+13035553210",
    saved: true,
  },
  {
    id: 8,
    images: [
      "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=500&q=80",
      "https://images.unsplash.com/photo-1512918728676-2e1ec7d1d19b?auto=format&fit=crop&w=500&q=80",
    ],
    price: 1600,
    name: "City Lights Apartments",
    address: "900 Broadway St, Los Angeles, CA",
    beds: 2,
    baths: 1,
    description: "Bright apartment in downtown Los Angeles, close to metro.",
    rules: "No pets. Quiet hours after 9pm.",
    size: 85,
    rooms: 4,
    hasKitchen: true,
    kitchens: 1,
    hasBathroom: true,
    bathrooms: 1,
    hasClimate: true,
    hasTV: false,
    hasTVWireless: false,
    map: "https://maps.google.com/?q=900+Broadway+St,+Los+Angeles,+CA",
    owner: {
      id: "owner8",
      name: "Olivia Hall",
      rating: 4.6,
    },
    cellphone: "+14155550000",
    saved: false,
  },
  {
    id: 9,
    images: [
      "https://images.unsplash.com/photo-1482062364825-616fd23b8fc1?auto=format&fit=crop&w=500&q=80",
      "https://images.unsplash.com/photo-1472224371017-08207f84aaae?auto=format&fit=crop&w=500&q=80",
    ],
    price: 2150,
    name: "Greenwood Estates",
    address: "250 Maple Ave, Seattle, WA",
    beds: 3,
    baths: 2,
    description: "Pet-friendly estates with garden and modern amenities.",
    rules: "Pets allowed. Quiet hours apply.",
    size: 115,
    rooms: 5,
    hasKitchen: true,
    kitchens: 1,
    hasBathroom: true,
    bathrooms: 2,
    hasClimate: false,
    hasTV: true,
    hasTVWireless: true,
    map: "https://maps.google.com/?q=250+Maple+Ave,+Seattle,+WA",
    owner: {
      id: "owner9",
      name: "Sophia Martin",
      rating: 4.8,
    },
    cellphone: "+13216549870",
    saved: true,
  },
  {
    id: 10,
    images: [
      "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=500&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=500&q=80",
    ],
    price: 2350,
    name: "Seaside Villas",
    address: "500 Beach Rd, San Diego, CA",
    beds: 4,
    baths: 3,
    description: "Beachfront villas with pool, perfect for families.",
    rules: "No pets. Quiet hours after 10pm.",
    size: 130,
    rooms: 7,
    hasKitchen: true,
    kitchens: 2,
    hasBathroom: true,
    bathrooms: 3,
    hasClimate: true,
    hasTV: true,
    hasTVWireless: false,
    map: "https://maps.google.com/?q=500+Beach+Rd,+San+Diego,+CA",
    owner: {
      id: "owner10",
      name: "Luke Wilson",
      rating: 4.9,
    },
    cellphone: "+14155559999",
    saved: true,
  },
];
