import { StyleSheet } from 'react-native';
import { Spacing } from './global';

export const spacingStyles = StyleSheet.create({
  p0: { padding: 0 },
  pXs: { padding: Spacing.xs },
  pSm: { padding: Spacing.sm },
  pMd: { padding: Spacing.md },
  pLg: { padding: Spacing.lg },
  pXl: { padding: Spacing.xl },
  p2xl: { padding: Spacing['2xl'] },
  p3xl: { padding: Spacing['3xl'] },
  
  pt0: { paddingTop: 0 },
  ptXs: { paddingTop: Spacing.xs },
  ptSm: { paddingTop: Spacing.sm },
  ptMd: { paddingTop: Spacing.md },
  ptLg: { paddingTop: Spacing.lg },
  ptXl: { paddingTop: Spacing.xl },
  pt2xl: { paddingTop: Spacing['2xl'] },
  
  pb0: { paddingBottom: 0 },
  pbXs: { paddingBottom: Spacing.xs },
  pbSm: { paddingBottom: Spacing.sm },
  pbMd: { paddingBottom: Spacing.md },
  pbLg: { paddingBottom: Spacing.lg },
  pbXl: { paddingBottom: Spacing.xl },
  pb2xl: { paddingBottom: Spacing['2xl'] },
  
  pl0: { paddingLeft: 0 },
  plXs: { paddingLeft: Spacing.xs },
  plSm: { paddingLeft: Spacing.sm },
  plMd: { paddingLeft: Spacing.md },
  plLg: { paddingLeft: Spacing.lg },
  plXl: { paddingLeft: Spacing.xl },
  
  pr0: { paddingRight: 0 },
  prXs: { paddingRight: Spacing.xs },
  prSm: { paddingRight: Spacing.sm },
  prMd: { paddingRight: Spacing.md },
  prLg: { paddingRight: Spacing.lg },
  prXl: { paddingRight: Spacing.xl },
  
  px0: { paddingHorizontal: 0 },
  pxXs: { paddingHorizontal: Spacing.xs },
  pxSm: { paddingHorizontal: Spacing.sm },
  pxMd: { paddingHorizontal: Spacing.md },
  pxLg: { paddingHorizontal: Spacing.lg },
  pxXl: { paddingHorizontal: Spacing.xl },
  
  py0: { paddingVertical: 0 },
  pyXs: { paddingVertical: Spacing.xs },
  pySm: { paddingVertical: Spacing.sm },
  pyMd: { paddingVertical: Spacing.md },
  pyLg: { paddingVertical: Spacing.lg },
  pyXl: { paddingVertical: Spacing.xl },
  
  m0: { margin: 0 },
  mXs: { margin: Spacing.xs },
  mSm: { margin: Spacing.sm },
  mMd: { margin: Spacing.md },
  mLg: { margin: Spacing.lg },
  mXl: { margin: Spacing.xl },
  
  mt0: { marginTop: 0 },
  mtXs: { marginTop: Spacing.xs },
  mtSm: { marginTop: Spacing.sm },
  mtMd: { marginTop: Spacing.md },
  mtLg: { marginTop: Spacing.lg },
  mtXl: { marginTop: Spacing.xl },
  
  mb0: { marginBottom: 0 },
  mbXs: { marginBottom: Spacing.xs },
  mbSm: { marginBottom: Spacing.sm },
  mbMd: { marginBottom: Spacing.md },
  mbLg: { marginBottom: Spacing.lg },
  mbXl: { marginBottom: Spacing.xl },
  
  ml0: { marginLeft: 0 },
  mlXs: { marginLeft: Spacing.xs },
  mlSm: { marginLeft: Spacing.sm },
  mlMd: { marginLeft: Spacing.md },
  mlLg: { marginLeft: Spacing.lg },
  mlXl: { marginLeft: Spacing.xl },
  
  mr0: { marginRight: 0 },
  mrXs: { marginRight: Spacing.xs },
  mrSm: { marginRight: Spacing.sm },
  mrMd: { marginRight: Spacing.md },
  mrLg: { marginRight: Spacing.lg },
  mrXl: { marginRight: Spacing.xl },
  
  mx0: { marginHorizontal: 0 },
  mxXs: { marginHorizontal: Spacing.xs },
  mxSm: { marginHorizontal: Spacing.sm },
  mxMd: { marginHorizontal: Spacing.md },
  mxLg: { marginHorizontal: Spacing.lg },
  mxXl: { marginHorizontal: Spacing.xl },
  
  my0: { marginVertical: 0 },
  myXs: { marginVertical: Spacing.xs },
  mySm: { marginVertical: Spacing.sm },
  myMd: { marginVertical: Spacing.md },
  myLg: { marginVertical: Spacing.lg },
  myXl: { marginVertical: Spacing.xl },
  
  gapXs: { gap: Spacing.xs },
  gapSm: { gap: Spacing.sm },
  gapMd: { gap: Spacing.md },
  gapLg: { gap: Spacing.lg },
  gapXl: { gap: Spacing.xl },
  gap2xl: { gap: Spacing['2xl'] },
});
